FROM node:latest as build-stage
WORKDIR /example-frontend
COPY ./example-frontend .
RUN npm install
RUN npm run build

FROM nginx as production-stage
RUN mkdir /example-frontend
COPY --from=build-stage /example-frontend/dist /example-frontend
COPY frontend-nginx.conf /etc/nginx/nginx.conf